name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup gcloud cli
        run: |
          wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
          tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --quiet --usage-reporting=false --path-update=true
          PATH="google-cloud-sdk/bin:${PATH}"
          gcloud --quiet components update

      - name: setup staging dir
        run: |
          mkdir staging
          cp ./main.py ./staging
          cp ./requirements.txt ./staging

      - name: deploy cloud function
        working-directory: ./staging
        run: |
          printf "%s" '${{ secrets.GCF_DEPLOYER_KEY }}' > key-file.json
          gcloud auth activate-service-account --key-file=key-file.json
          rm key-file.json
          gcloud functions deploy bank-statement-reader \
          --runtime python39 \
          --entry-point process_bank_statement \
          --region us-central1 \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --allow-unauthenticated \
          --no-gen2 \
          --memory 128MB \
          --trigger-http \
          --security-level secure-always \
          --set-env-vars GOTYME_BS_PASSWORD="${{ secrets.GOTYME_BS_PASSWORD }}",NOTION_ORGANIZATION="${{ secrets.NOTION_ORGANIZATION }}",NOTION_EXPENSES_DATABASE_ID="${{ secrets.NOTION_EXPENSES_DATABASE_ID }}",NOTION_EXPENSES_VIEW_ID="${{ secrets.NOTION_EXPENSES_VIEW_ID }}",DISCORD_ALERT_PUBSUB_TOPIC="${{ secrets.DISCORD_ALERT_PUBSUB_TOPIC }}",DISCORD_ALERTS_CHANNEL_NAME="${{ secrets.DISCORD_ALERTS_CHANNEL_NAME }}",PROJECT="${{ secrets.GCP_PROJECT_ID }}"
